FROM oven/bun:1.2 AS deps
WORKDIR /app
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

FROM oven/bun:1.2 AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_SITE_URL=https://dreamvalleypublications.com
ARG NEXT_PUBLIC_COMPANY_NAME="Dream Valley Publications"
ARG NEXT_PUBLIC_COMPANY_SHORT_NAME="Dream Valley"
ARG NEXT_PUBLIC_SUPPORT_EMAIL=support@dreamvalleypublications.com
ARG NEXT_PUBLIC_CONSULTATION_EMAIL=consult@dreamvalleypublications.com
ARG NEXT_PUBLIC_SUPPORT_PHONE="+91 90000 00000"
ARG NEXT_PUBLIC_PRIMARY_REGION=India
ARG NEXT_PUBLIC_PRIMARY_TIMEZONE="IST (UTC+05:30)"
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_COMPANY_NAME=$NEXT_PUBLIC_COMPANY_NAME
ENV NEXT_PUBLIC_COMPANY_SHORT_NAME=$NEXT_PUBLIC_COMPANY_SHORT_NAME
ENV NEXT_PUBLIC_SUPPORT_EMAIL=$NEXT_PUBLIC_SUPPORT_EMAIL
ENV NEXT_PUBLIC_CONSULTATION_EMAIL=$NEXT_PUBLIC_CONSULTATION_EMAIL
ENV NEXT_PUBLIC_SUPPORT_PHONE=$NEXT_PUBLIC_SUPPORT_PHONE
ENV NEXT_PUBLIC_PRIMARY_REGION=$NEXT_PUBLIC_PRIMARY_REGION
ENV NEXT_PUBLIC_PRIMARY_TIMEZONE=$NEXT_PUBLIC_PRIMARY_TIMEZONE
RUN bun run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=8080
ENV HOSTNAME=0.0.0.0
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
EXPOSE 8080
CMD ["node", "server.js"]
